# Generated by Django 5.1.7 on 2025-03-25 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand_en',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_ky',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_ru',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='model_en',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='model_ky',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='model_ru',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.CreateModel(
            name='CarPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/')),
                ('home_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_photos', to='mysite.car')),
            ],
        ),
    ]
